global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-monitoring-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:8080"]
        labels:
          application: "api-monitoring"

